# IMPORT LIBRARY


In [5]:
import tensorflow as tf
import numpy as np


## tensor shape(5,5) dengan nilai random disimpan dalam variable random_tensor

In [6]:
rn_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1) #createe tensor use  tf.random.normal
rn_tensor.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

##  Tensor shape(5,5) dari list, nilai bilangan prima dalam variable prime_tensor

In [7]:
list_prima = [[2, 4, 6, 8, 10],[12, 14, 16,18,20],[30, 32, 34, 36, 38],[50, 52, 54, 56, 58],[60, 62, 64, 66, 68]]

prima_tensor = tf.constant(list_prima, dtype=tf.float32) #create tensor use tf.constant
prima_tensor.numpy()

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [30., 32., 34., 36., 38.],
       [50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.]], dtype=float32)

## Menampilkan dimensi dari kedua variable tersebut

In [8]:
rn_tensor.shape

TensorShape([5, 5])

In [10]:
prima_tensor.shape

TensorShape([5, 5])

## Menampilkan hasil perhitungan aritmetika 2 variable (5 operator)

In [13]:
print("Penjumlahan :",tf.add(prima_tensor,rn_tensor))

Penjumlahan : tf.Tensor(
[[ 1.6761351  4.991337   6.1402426  9.257397  10.099923 ]
 [12.189833  13.712888  14.25864   19.871876  17.98955  ]
 [28.532698  30.7278    33.219627  36.94073   37.93835  ]
 [47.91575   52.61423   52.54891   55.113064  57.032593 ]
 [60.94832   61.30255   64.53915   65.4703    65.98946  ]], shape=(5, 5), dtype=float32)


In [14]:
print("Pengurangan :",tf.subtract(prima_tensor,rn_tensor))

Pengurangan : tf.Tensor(
[[ 2.323865   3.0086632  5.8597574  6.742603   9.900077 ]
 [11.810167  14.287112  17.74136   16.128124  22.01045  ]
 [31.467302  33.272198  34.780373  35.05927   38.06165  ]
 [52.08425   51.38577   55.45109   56.886936  58.967407 ]
 [59.05168   62.69745   63.460857  66.5297    70.01054  ]], shape=(5, 5), dtype=float32)


In [15]:
print("Perkalian :",tf.multiply(prima_tensor,rn_tensor))

Perkalian : tf.Tensor(
[[  -0.64772975    3.9653478     0.841456     10.059177      0.9992335 ]
 [   2.277987     -4.019567    -27.861752     33.693756    -40.209007  ]
 [ -44.01909     -40.710365    -26.53271      33.86629      -2.3426325 ]
 [-104.21263      31.94003     -78.35897     -49.668373    -56.109703  ]
 [  56.8991      -43.241894     34.505196    -34.960243   -136.71648   ]], shape=(5, 5), dtype=float32)


In [16]:
print("Pembagian :",tf.divide(prima_tensor,rn_tensor))

Pembagian : tf.Tensor(
[[  -6.175415     4.034955    42.782986     6.3623495  100.076706 ]
 [  63.21371    -48.76147     -9.188224     9.616025    -9.94802  ]
 [ -20.445677   -25.1533     -43.568863    38.26814   -616.4006   ]
 [ -23.989414    84.65865    -37.213352   -63.13877    -59.95398  ]
 [  63.26989    -88.89527    118.706764  -124.59868    -33.82182  ]], shape=(5, 5), dtype=float32)


In [17]:
print("Pangkat :",tf.pow(prima_tensor,rn_tensor))

Pangkat : tf.Tensor(
[[7.98926711e-01 3.95224905e+00 1.28567147e+00 1.36628971e+01
  1.25870323e+00]
 [1.60274112e+00 4.68741030e-01 8.00192077e-03 2.23724594e+02
  2.42294627e-03]
 [6.80167181e-03 1.21660568e-02 6.38078302e-02 2.91112576e+01
  7.99114764e-01]
 [2.87685107e-04 1.13246050e+01 3.06293136e-03 2.81494837e-02
  1.96808781e-02]
 [4.85571823e+01 5.62207401e-02 9.41435432e+00 1.08689204e-01
  2.06858836e-04]], shape=(5, 5), dtype=float32)


## Nilai maksimal dan minimal dari variable random_tensor

In [18]:
tf.argmax(rn_tensor, axis=1). numpy() #nilai max dari kolom(axis=1)

array([3, 3, 3, 1, 0], dtype=int64)

In [20]:
tf.argmin(rn_tensor, axis=1). numpy() #nilai min dari kolom(axis=1)

array([0, 4, 0, 0, 4], dtype=int64)

In [22]:
tf.argmax(rn_tensor, axis=0). numpy() #nilai max dari baris(axis=0)

array([4, 0, 4, 1, 0], dtype=int64)

In [24]:
tf.argmin(rn_tensor, axis=0). numpy() #nilai min dari baris(axis=0)

array([3, 2, 1, 3, 4], dtype=int64)

## Penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [26]:
tf.concat([rn_tensor, prima_tensor], axis=1) #penggabungan kolom

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-3.2386488e-01,  9.9133694e-01,  1.4024267e-01,  1.2573972e+00,
         9.9923350e-02,  2.0000000e+00,  4.0000000e+00,  6.0000000e+00,
         8.0000000e+00,  1.0000000e+01],
       [ 1.8983224e-01, -2.8711194e-01, -1.7413595e+00,  1.8718754e+00,
        -2.0104504e+00,  1.2000000e+01,  1.4000000e+01,  1.6000000e+01,
         1.8000000e+01,  2.0000000e+01],
       [-1.4673029e+00, -1.2721989e+00, -7.8037381e-01,  9.4073033e-01,
        -6.1648224e-02,  3.0000000e+01,  3.2000000e+01,  3.4000000e+01,
         3.6000000e+01,  3.8000000e+01],
       [-2.0842526e+00,  6.1423135e-01, -1.4510920e+00, -8.8693523e-01,
        -9.6740866e-01,  5.0000000e+01,  5.2000000e+01,  5.4000000e+01,
         5.6000000e+01,  5.8000000e+01],
       [ 9.4831836e-01, -6.9744992e-01,  5.3914368e-01, -5.2970064e-01,
        -2.0105364e+00,  6.0000000e+01,  6.2000000e+01,  6.4000000e+01,
         6.6000000e+01,  6.8000000e+01]], dtype=float32)>

In [28]:
tf.concat([rn_tensor, prima_tensor], axis=0) #penggabungan baris

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-3.2386488e-01,  9.9133694e-01,  1.4024267e-01,  1.2573972e+00,
         9.9923350e-02],
       [ 1.8983224e-01, -2.8711194e-01, -1.7413595e+00,  1.8718754e+00,
        -2.0104504e+00],
       [-1.4673029e+00, -1.2721989e+00, -7.8037381e-01,  9.4073033e-01,
        -6.1648224e-02],
       [-2.0842526e+00,  6.1423135e-01, -1.4510920e+00, -8.8693523e-01,
        -9.6740866e-01],
       [ 9.4831836e-01, -6.9744992e-01,  5.3914368e-01, -5.2970064e-01,
        -2.0105364e+00],
       [ 2.0000000e+00,  4.0000000e+00,  6.0000000e+00,  8.0000000e+00,
         1.0000000e+01],
       [ 1.2000000e+01,  1.4000000e+01,  1.6000000e+01,  1.8000000e+01,
         2.0000000e+01],
       [ 3.0000000e+01,  3.2000000e+01,  3.4000000e+01,  3.6000000e+01,
         3.8000000e+01],
       [ 5.0000000e+01,  5.2000000e+01,  5.4000000e+01,  5.6000000e+01,
         5.8000000e+01],
       [ 6.0000000e+01,  6.2000000e+01,  6.4000000e+01,  6.6000000e+01,
      

## Hasil sorting kedua variable di atas. (descending)

In [30]:
sort_rn_tensor1 = tf.sort(rn_tensor, direction="DESCENDING") 
sort_rn_tensor1.numpy()

array([[ 1.2573972 ,  0.99133694,  0.14024267,  0.09992335, -0.32386488],
       [ 1.8718754 ,  0.18983224, -0.28711194, -1.7413595 , -2.0104504 ],
       [ 0.94073033, -0.06164822, -0.7803738 , -1.2721989 , -1.4673029 ],
       [ 0.61423135, -0.88693523, -0.96740866, -1.451092  , -2.0842526 ],
       [ 0.94831836,  0.5391437 , -0.52970064, -0.6974499 , -2.0105364 ]],
      dtype=float32)

In [31]:
sort_prima_tensor1 = tf.sort(prima_tensor, direction="DESCENDING")
sort_prima_tensor1.numpy()

array([[10.,  8.,  6.,  4.,  2.],
       [20., 18., 16., 14., 12.],
       [38., 36., 34., 32., 30.],
       [58., 56., 54., 52., 50.],
       [68., 66., 64., 62., 60.]], dtype=float32)

In [33]:
sort_rn_tensor2 = tf.argsort(rn_tensor, direction="DESCENDING") 
sort_rn_tensor2.numpy()

array([[3, 1, 2, 4, 0],
       [3, 0, 1, 2, 4],
       [3, 4, 2, 1, 0],
       [1, 3, 4, 2, 0],
       [0, 2, 3, 1, 4]])

In [34]:
sort_prima_tensor2 = tf.argsort(prima_tensor, direction="DESCENDING")
sort_prima_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])